title: "Dr. Ramya Vijay"
description: "Academic Portfolio | Research | Publications | Projects"
theme: jekyll-theme-minimal

# Optional: add your social links
github_username: your-github-username
linkedin_username: your-linkedin-id
